### ISSUE TITLE
add support for custom "base" url

### ISSUE THREAD

**Issue by chen23** [f5devcentral/terraform-aws-bigip-module#12]
there are customer environments where access to the public internet is restricted.  It would be helpful to allow an end-user to override the base URL of where the RPM/bigip-runtime-init are downloaded from to allow one to run in a restricted environment w/out having to override user_data

**Comment by nmenant** [comment]
Hi Eric,
when looking at our code, we provide this ability for our extension via the https://github.com/f5devcentral/terraform-aws-bigip-module/blob/master/variables.tf file. 

```
variable DO_URL {
  description = "URL to download the BIG-IP Declarative Onboarding module"
  type        = string
  default     = "https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.16.0/f5-declarative-onboarding-1.16.0-8.noarch.rpm"
}
## Please check and update the latest AS3 URL from https://github.com/F5Networks/f5-appsvcs-extension/releases/latest 
# always point to a specific version in order to avoid inadvertent configuration inconsistency
variable AS3_URL {
  description = "URL to download the BIG-IP Application Service Extension 3 (AS3) module"
  type        = string
  default     = "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.23.0/f5-appsvcs-3.23.0-5.noarch.rpm"
}

## Please check and update the latest TS URL from https://github.com/F5Networks/f5-telemetry-streaming/releases/latest 
# always point to a specific version in order to avoid inadvertent configuration inconsistency
variable TS_URL {
  description = "URL to download the BIG-IP Telemetry Streaming module"
  type        = string
  default     = "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.15.0/f5-telemetry-1.15.0-4.noarch.rpm"
}
```

https://github.com/f5devcentral/terraform-aws-bigip-module/blob/master/main.tf

```
  # build user_data file from template
  user_data = var.custom_user_data != null ? var.custom_user_data : templatefile(
    "${path.module}/f5_onboard.tmpl",
    {
      DO_URL         = var.DO_URL,
      AS3_URL        = var.AS3_URL,
      TS_URL         = var.TS_URL,
      CFE_URL        = var.CFE_URL,
      FAST_URL       = var.fastPackageUrl
      libs_dir       = var.libs_dir,
      onboard_log    = var.onboard_log,
      bigip_username = var.f5_username
      bigip_password = var.aws_secretmanager_auth ? data.aws_secretsmanager_secret_version.current[0].secret_string : random_string.dynamic_password.result
    }
  )
  depends_on = [aws_eip.mgmt, aws_network_interface.public, aws_network_interface.private]

  tags = {
    Name = format("%s-%d", local.instance_prefix, count.index)
  }
}
```

We are transitioning to bigip-runtime-init and we will make sure this is covered also since it has this ability based on this (example): https://github.com/F5Networks/f5-bigip-runtime-init#azure-terraform-snippet

``` 
extension_services:
  service_operations:
    - extensionType: do
      type: url
      value: https://raw.githubusercontent.com/F5Networks/f5-bigip-runtime-init/main/examples/declarations/do_w_admin.json
    - extensionType: as3
      type: url
      value: https://raw.githubusercontent.com/F5Networks/f5-bigip-runtime-init/main/examples/declarations/as3.json
``` 

As long as we provide this ability to retrieve bigip-runtime-init and those extensions, i believe we will meet your requirements, could you confirm ?
